/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package selfExecutingCmdLine;

import java.io.*;
import java.util.*;
/**
 *
 * @author aritra_dhar
 */
public class ToStringScanner 
{
    String inputDir;
    String outputDir;
    String []file;

    public void setInputDir(String inputDir) {
        this.inputDir = inputDir;
    }

    public void setOutputDir(String outputDir) {
        this.outputDir = outputDir;
        //System.out.println(this.outputDir);
    }
    
    public void setFile()
    {
        File []f=new File(outputDir.concat("\\datalog\\")).listFiles();
        String []file=new String[f.length];
        for(int i=0;i<f.length;i++)
            file[i]=f[i].toString();
        this.file=file;
    }
    
    public void scanner() throws Exception
    {
        BufferedReader []br=new BufferedReader[file.length];
        BufferedReader []br1=new BufferedReader[file.length];
        FileWriter fwrite=new FileWriter("tmp_rule_file.txt",true);
        HashSet<String> type_set=new HashSet<String>();
        
        fwrite.append("\n//autogenerated knowledgebase");
        
        for(int i=0;i<file.length;i++)
        {
            br[i]=new BufferedReader(new FileReader(file[i]));
            String a="";
            int st=0,k=0;
            while((a=br[i].readLine())!=null)
            {
                if(a.contains("SetType"))
                    st++;
            }
            br[i].close();
            
            br1[i]=new BufferedReader(new FileReader(file[i]));
            String []S=new String[st];
            while((a=br1[i].readLine())!=null)
            {
                if(a.contains("SetType"))
                {
                    int dl_st=0,dl_en=0,cn=0;
                    for(int j=0;j<a.length();j++)
                    {
                        if(a.charAt(j)=='\'')
                        {
                            cn++;
                            if(cn==5)
                                dl_st=j+1;
                            if(cn==6)
                                dl_en=j;
                        }
                    }
                    String type=a.substring(dl_st, dl_en);
                    S[k++]=type;
                    //System.out.println(type); 
                    //fwrite.append("\nPropTaint('"+type+"','toString').");
                    if(!type_set.contains(type))
                    {
                        type_set.add(type);
                        fwrite.append("\nPropTaint('"+type+"','toString').");
                    }
                }
            }
            br1[i].close();
        }
        fwrite.close();
    }
}
